export const ServicesTitle:any = {
    Assembly_service:[
    'Furniture assembly (assembly of cabinets, shelves, beds, etc.)',
    'Kitchen installation (kitchen furniture, appliances, etc.)',
    'Assembly of wardrobes and storage systems',
    'Hanging of pictures, mirrors, and wall decorations',
    'Installation of lamps and light fixtures',
    'Installation of curtains, blinds, and sun protection systems',
    'Household repairs (e.g., damaged doors, cabinets)',
    'Mounting of TV brackets and entertainment electronics',
    'General handyman tasks (drilling, anchoring, minor repairs)',
    'Consultation and assistance with renovation projects'
   ],
   Air_conditioning_technician:[
    ' Installation of air condition systems (split, multi-split, central)',
    'Maintenance and servicing of air conditioning systems',
    'Repair of air conditioning systems',
    'Air conditioning for residential and office spaces',
    'Air conditioning for commercial or industrial spaces',
    'Air conditioning for server rooms',
    'Installation of ventilation systems',
    'Maintenance and servicing of ventilation systems',
    'Air purification systems and filter replacement',
    'Energy efficiency consulting & optimization of climate systems',
    'Consultation for selecting and planning climate solutions'
   ],
   Bricklayers_builders:[
    'Construction of masonry structures (houses, buildings, walls)',
    'Restoration and repair of masonry',
    'Installation of paving stones and sidewalks',
    'Construction of foundations and basement walls',
    'Concrete work (formwork, pouring concrete)',
    'Screeding work (floor screeding, leveling)',
    'Drywall installation (walls, ceilings, partition walls)',
    'Plastering work (interior and exterior plaster)',
    'Facade work and facade design',
    'Waterproofing work (e.g., moisture sealing)',
    'Consultation for construction projects and material selection'
   ],
   Building_cleaning:[
    'Office and commercial cleaning',
    'Staircase cleaning',
    'Window cleaning',
    'Carpet and upholstery cleaning',
    'Construction cleaning',
    'Deep cleaning and floor restoration',
    'Facade cleaning',
    'Industrial cleaning',
    'Glass and mirror cleaning',
    'Hygiene and disinfection measures',
    'Pest control',
    'Special cleaning (e.g., after events)',
   ],
   Construction_planner:[
    'Construction planning and design',
    'Construction consultancy and project management',
    'Building permits and regulatory approvals',
    'Energy efficiency consultancy',
    'Architectural design and space planning',
    'Construction cost and budget planning',
    'Construction supervision and management',
    'Construction monitoring and quality control',
    'Sustainability and environmental consultancy',
   ],
   Carpenters:[
    'Custom furniture manufacturing (cabinets, shelves, tables)',
    'Installation of kitchen furniture and cabinets',
    'Manufacturing and installation of stairs and railings',
    'Creation of custom-built wardrobes and walk-in closets',
    'Restoration of antique furniture pieces',
    'Repair and maintenance of wooden furniture',
    'Manufacturing and installation of windows and doors',
    'Construction of custom wooden structures',
    'Consultation on wood species selection and surface treatment',
   ],
   Chimney_builders:[
    'Planning and consultation for fireplace systems',
    'Installation of wood-burning stoves and fireplaces',
    'Chimney renovation and repair',
    'Chimney cap and cover works',
    'Fireplace cladding and cladding materials',
    'Chimney caps and flue pipes',
    'Fireplace refurbishment and cleaning',
    'Fireplace fire suppression',
    'Maintenance and inspection of fireplace systems',
    'Consultation for selecting fireplace models and options',
   ],
   Construction_companies:[
    'New construction of residential buildings',
    'Commercial and industrial construction',
    'Renovation and remodeling of existing buildings',
    'Turnkey construction',
    'Construction planning and architectural services',
    'Project management and construction supervision',
    'High-rise construction (skyscraper, apartment, office building)',
    'Civil engineering (roads, sewage systems, foundations)', 
    'Facade construction and building envelope',
    'Interior finishing and drywall',
    'Construction of outdoor facilities and landscaping',
    'Energy-saving and sustainability solutions'
   ],
   Concrete_drillers:[
    'Concrete drilling for installations (e.g., pipelines, cables)',
    'Core drilling for penetrations and openings',
    'Concrete cutting for partition walls, ceilings, and floors',
    'Joint cutting for expansions and dilations',
    'Concrete milling for surface smoothing and preparation',
    'Sawing for concrete demolition and removal',
    'Concrete removal and dismantling',
    'Concrete crack repair and rehabilitation',
    'Specialized services (e.g.concrete compaction, temperature measurement)',
   ],
   Climate_technicians:[
    'Installation of a new heating system',
    'Repair or maintenance of an existing heating system',
    'Installation of an air conditioning unit or HVAC system',
    'Repair or maintenance of an air conditioning unit or HVAC system',
    'Ventilation system installation or maintenance',
    'Heat pump installation or repair',
    'Thermostat installation or troubleshooting',
    'Air filter replacement or indoor air quality improvement',
    'Energy efficiency consultation and optimization'
],
   Car_workshops:[
    'Inspection and maintenance',
    'Engine and drivetrain repair',
    'Brake and suspension service',
    'Diagnosis and troubleshooting',
    'Oil change and filter replacement',
    'Tire replacement and tire service',
    'Air conditioning service and maintenance',
    'Bodywork and painting',
    'Windshield repair and replacement',
    'Electrical and electronic repairs',
    'Vehicle inspection (MOT) and emissions testing',
    'Consultation for car purchase and vehicle selection'
   ],
   Drywallers:[
    'Installation of drywall walls and ceilings',
    'Installation of partition walls and room dividers',
    'Installation of insulation (thermal, acoustic, or fire protection)',
    'Cladding of pipes and installations',
    'Installation of drywall systems (e.g., cladding)',
    'Construction of drywall and gypsum board structures',
    'Drywall works for interior finishing (e.g., built-in cabinets)',
    'Fire protection measures and fireproof cladding',
    'Repair and renovation of drywall structures',
    'Consultation on selection of drywall materials and techniques',
   ],
   Demolition_and_disposal:[
    'Complete demolition of buildings and structures',
    'Partial demolition/dismantling of buildings',
    'Asbestos removal',
    'Disposal and recycling of construction materials',
    'Hazardous waste disposal',
    'Container and waste disposal',
    'Construction site cleaning',
   ],
   E_lectrician:[
    'Electrical installations for new constructions',
    'Electrical inspection and certification',
    'Electrical installations for renovations and remodeling',
    'Electrical repairs and maintenance',
    'Fuse box installation and upgrade',
    'Lighting installation (indoor and outdoor)',
    'Outlet and switch installation',
    'Network and data cable installation',
    'Video surveillance systems',
    'Alarm system installation',
    'Smart home integration',
    'Troubleshooting and fault finding'
   ],
   Earthmoving_companies:[
    'Excavation and earthworks',
    'Site leveling and soil preparation',
    'Construction of excavations and foundations',
    'Sewer and pipeline construction',
    'Road and pathway construction',
    'Excavation and demolition works',
    'Landscaping and gardening',
    'Pond construction and water features',
    'Drainage and dewatering systems',
    'Site preparation and excavation',
    'Soil compaction and stabilization',
    'Debris and waste disposal',
   ],
   Fence_builders:[
    'Construction of fences (wood, metal, plastic, etc.)',
    'Installation of garden and property fences',
    'Installation of privacy screens and fences',
    'Fence repair and maintenance',
    'Installation of gates and driveway gates',
    'Construction of gabions and noise barriers',
    'Consultation on the selection of fence materials and designs',
    'Custom fence solutions',
    'Fence greening and planting of climbing plants',
   ],
   Flooring_installer:[
    'Installation of flooring materials (e.g. hardwood, laminate, tiles)',
    'Screed works (e.g., substrate preparation, screed installation)',
    'Industrial floor coatings',
    'Flooring renovation and repairs',
    'Terrace and balcony coverings',
    'Installation and integration of underfloor heating',
    'Staircase cladding and renovation',
    'Barrier-free flooring solutions',
    'Soundproofing and impact sound insulation',
    'Consultation for selecting the appropriate flooring materials',
   ],
   Glazier:[
    'Installation of windows and doors',
    'Glass repair and glass damage restoration',
    'Glass cutting and custom fitting',
    'Mirror installation and fabrication',
    'Glass partitions and room dividers',
    'Glass showers and shower enclosures',
    'Glass tables and glass panels',
    'Safety glass and burglary protection solutions',
    'Shop windows and display cases',
    'Winter garden glazing',
    'Consultation on glass types and solutions'
   ],
   Heating_installers:[
    'Installation of heating systems (gas, oil, or district heating)',
    'Installation of underfloor heating',
    'Installation of radiators and radiator replacement',
    'Maintenance and repair of heating systems',
    'Optimization and energy efficiency consulting',
    'Installation of thermostats and control systems',
    'Condensing technology and integration of solar systems',
    'Ventilation and installation of heating pipes',
    'Emergency repairs in case of heating failure',
    'Consultation for the selection of heating systems',
   ],
   Interior_designers:[
    'Space concept and space planning',
    'Color and material consultation',
    'Furniture and furnishing planning',
    'Lighting design',
    'Interior construction and renovation',
    'Wall design and wallpaper',
    'Flooring and floor planning',
    'Window and window decoration',
    'Acoustic and soundproofing solutions',
    'Barrier-free design',
    '3D visualization and presentation',
    'Consultation for furniture and accessory selection'
   ],
   Interior_decorators:[
    'Flooring (carpet, laminate, hardwood, tiles, etc.)',
    'Wall decoration (wallpapers, paint, wall claddings)',
    'Window treatments (curtains, drapes, blinds, shades)',
    'Sun protection (awnings, pleated blinds, shutters)',
    'Upholstery services (furniture reupholstery, upholstery repairs)',
    'Interior planning and design',
    'Acoustic solutions (soundproofing, room acoustics)',
    'Room division and space planning',
    'Custom-made furniture and furnishings',
    'Consultation on material selection and designs'
   ],
   k_itchen_fitters:[
    'Full kitchen installation (including cabinets, countertops, appliances, etc.)',
    'Kitchen cabinet installation or replacement',
    'Countertop installation or replacement',
    'Kitchen appliance installation',
    'Backsplash installation',
    'Flooring installation or replacement',
    'Kitchen island installation',
    'Custom kitchen carpentry work',
   ],
   Landscape_builders:[
    'Garden planning and design',
    'Lawn installation and maintenance',
    'Planting and tree care',
    'Pond and water garden construction',
    'Terrace and pathway construction',
    'Wall and stonework',
    'Garden lighting and outdoor fixtures',
    'Privacy screens and fence installations',
    'Garden irrigation systems',
    'Roof greening and green roof installation',
    'Garden maintenance and upkeep',
    'Consultation for selecting plants and garden solutions',
   ],
   Moving_companies:[
    'Moving planning and organization',
    'Provision of moving supplies (boxes, packing materials)',
    'Packing service (packing of items and furniture)',
    'Disassembly and assembly of furniture',
    'Transportation of furniture and belongings',
    'Loading and unloading of belongings',
    'Furniture assembly and disassembly at the new location',
    'End-of-tenancy cleaning of the old apartment or premises',
    'Storage of furniture or belongings',
    'Moving assistance for senior or individual with limited mobility',
   ],
   Metal_fabricators:[
    'Manufacturing and installation of metal structures',
    'Metalwork for stairs, railings, and balconies',
    'Welding and metal repair',
    'Production and installation of metal fences and gates',
    'Manufacturing of metal facades and cladding',
    'Metal fabrication (cutting, bending, welding)',
    'Custom fabrication and installation of steel structures',
    'Production of custom metal components',
    'Installation of metal windows and doors',
    'Consultation for selecting metal materials and designs',
   ],
   Plasterers:[
    'Interior plastering (smooth, textured, lime plaster etc.)',
    'Exterior plastering (base plaster, facade plaster)',
    'Thermal insulation plaster (ETICS)',
    'Renovation plastering (for moisture damage or mold infestation)',
    'Repair of plaster damage (cracks, chipping)',
    'Skimming and smoothing walls and ceilings',
    'Plastering of drywall partitions',
    'Plaster coatings and finishes',
    'Consultation on the selection of plaster types and techniques',
   ],
   Paving_builders:[
    'Installation of paving stones and sidewalk tiles',
    'Construction of driveways, parking lots, and courtyard surface',
    'Design of terraces and outdoor areas',
    'Construction of natural stone walls and gabions',
    'Asphalt work (repairs, new road construction)',
    'Construction of footpaths and bicycle paths',
    'Construction of drainage systems and channels',
    'Creation of concrete surfaces (walkways, squares)',
    'Consultation for selecting materials and designs',
    'Renovation and maintenance of paving and road surfaces',
   ],
   Pool_builders:[
    'Consultation and planning for pool construction',
    'Construction of new swimming pools',
    'Installation of pre-made pools or custom-designed pools',
    'Installation of pool equipment (filtration system, pump, heater)',
    'Installation of pool tiles or pool liners',
    'Construction of pool decks and pool surroundings',
    'Designing pool landscapes and pool lighting',
    'Pool maintenance and cleaning',
    'Repair and renovation of existing pools',
    'Consultation on selection of pool accessories and equipment'
   ],
   Painters_decorators:[
    'Interior painting of walls and ceilings',
    'Exterior painting of facades',
    'Painting of doors, windows, and wooden surfaces',
    'Wallpapering and wall coverings',
    'Spackling and plastering',
    'Mold removal and moisture remediation',
    'Color consultation and color concepts',
    'Decorative painting techniques (e.g., glazing, stucco)',
    'Painting of metal surfaces (e.g., railings, stairs)',
    'Floor coatings and industrial painting',
    'Facade cleaning and protection',
    'Consultation for selecting colors and materials'
   ],
   Plumbing_installers:[
    'Installation of plumbing fixtures (sink, toilet, shower, bathtub)',
    'Repair of water pipes and connections',
    'Replacement or installation of faucets and fittings',
    'Installation of water heaters and boilers',
    'Installation and maintenance of heating systems',
    'Installation and repair of wastewater and sewage systems',
    'Renovation of bathrooms and sanitary facilities',
    'Installation of water treatment systems (e.g., water softeners)',
    'Accessibility adaptations for bathrooms (e.g. walk-in showers)',
    'Consultation on selection of plumbing product and installation',
   ],
   Roofer:[
    'Roof installation and replacement',
    'Roof repair and maintenance',
    'Roof restoration and renovation',
    'Gutter installation and repair',
    'Roof insulation and insulation',
    'Skylight installation and replacement',
    'Facade cladding and repair',
    'Chimney sealing and repair',
    'Roof coating and cleaning',
    'Storm damage repairs'
   ],
   Scaffolding_builders:[
    'Scaffolding for construction and renovation projects',
    'Facade scaffolding',
    'Scaffolding for high-rise and civil engineering projects',
    'Event scaffolding',
    'Specialized scaffolding (e.g., for bridges, towers)',
    'Weather protection and enclosures',
    'Scaffolding rental',
    'Scaffolding dismantling and removal',
    'Scaffold inspection and safety checks',
    'Scaffold maintenance and repairs',
    'Consultation for scaffold planning'
   ],
   Staircase_construction:[
    'Planning and design of custom staircase solutions',
    'Construction of new staircases (wood, metal, concrete, etc.)',
    'Renovation and refurbishment of existing staircases',
    'Installation of stair railings and handrails',
    'Staircase step and landing coverings (wood, stone, tiles, etc.)',
    'Custom-made staircase constructions',
    'Staircase remodeling and expansion',
    'Consultation on selection of staircase materials and designs'
   ],
   Saddlers_upholsterers:[
    'Upholstery work (reupholstering of furniture, chairs)',
    'Repair and restoration of upholstered furniture',
    'Custom-made upholstery furniture manufacturing',
    'Production of seat cushions and backrests',
    'Creation of covers for car seat upholstery',
    'Upholstery work for boats and yachts',
    'Saddlery work (reupholstering of car seats, motorcycle seats)',
    'Custom saddlebags and leather accessories manufacturing',
    'Restoration of antique furniture and leather goods',
    'Consultation on selection of fabrics & types of leather'
   ],
   Tiler:[
    'Tile installation for floors',
    'Tile installation for walls',
    'Tile installation for kitchens and bathrooms',
    'Terrace and balcony tiling',
    'Natural stone installation',
    'Mosaic and decorative tiles',
    'Tile cutting and fitting',
    'Grout sealing and sealing',
    'Tile renovation and repair',
    'Barrier-free solutions for floors and showers',
    'Consultation for selecting tiles and designs'
   ],
   Transport_companies:[
    'Moving services (residential or commercial relocation)',
    'Furniture transport and assembly',
    'Local and regional deliveries and transports',
    'Long-distance transportation (national or international)',
    'Express deliveries and courier services',
    'Transport of bulky or heavy goods',
    'Warehousing and storage services',
    'Disposal services (waste disposal, scrap removal)',
    'Specialized transportation (e.g. hazardous materials transport)',
    'Consultation and planning of transportation solutions.',
   ],
   Well_builders:[
    'Drilling of drinking water wells',
    'Wells for agricultural purposes',
    'Wells for irrigation systems',
    'Wells for geothermal heating and cooling systems',
    'Wells for industrial purposes',
    'Well maintenance and repairs',
    'Pump selection and installation',
    'Water quality testing and analysis',
    'Consultation for well selection and planning',
   ],
   Window_construction:[
    'Window manufacturing and installation',
    'Door manufacturing and installation',
    'Awning manufacturing and installation',
    'Roller shutter installation and repair',
    'Conservatory construction and glazing',
    'Glass and glazing works',
    'Insect screen installation',
    'Burglary protection solutions',
    'Barrier-free solutions for windows and doors',
    'Sun protection solutions (e.g., blinds, pleated blinds)',
    'Window and door repair and maintenance',
    'Consultation for selecting windows, doors, and awnings.'
   ],
   Wood_preservation:[
    'Wood preservation and wood impregnation',
    'Building protection against moisture and mold',
    'Pest control in the wood and construction sector',
    'Structural sealing and coating',
    'Basement waterproofing and moisture remediation',
    'Facade impregnation and protection',
    'Balcony and terrace coating',
    'Wood restoration and repair',
    'Roof truss renovation and protection',
    'Consultation on damage prevention',
   ]
}